// Language names in their native scripts
const LANGUAGE_NAMES = {
    'en': 'English',
    'de': 'Deutsch',
    'pl': 'Polski',
    'fr': 'Français',
    'es': 'Español',
    'el': 'Ελληνικά',
    'lv': 'Latviešu',
    'lt': 'Lietuvių',
    'nl': 'Nederlands',
    'zh': '繁體中文',
    'it': 'Italiano',
    'sv': 'Svenska',
    'sk': 'Slovensky',
    'pt': 'Português',
    'sl': 'Slovenščina',
    'ru': 'Русский',
    'da': 'Dansk',
    'fi': 'Suomi',
    'bg': 'Български',
    'cs': 'Čeština',
    'et': 'Eesti',
    'hu': 'Magyar',
    'ro': 'Română',
    'ja': '日本語',
    'ko': '한국어',
    'id': 'Bahasa Indonesia',
    'ne': 'नेपाली',
    'ab': 'Аҧсуа',
    'aa': 'Afar',
    'af': 'Afrikaans',
    'sq': 'Shqip',
    'ar': 'العربية',
    'hy': 'Հայերեն',
    'az': 'Azərbaycan',
    'bs': 'Bosanski',
    'tl': 'Tagalog',
    'hi': 'हिन्दी',
    'ka': 'ქართული',
    'hr': 'Hrvatski',
    'sr': 'Српски',
    'th': 'ไทย',
    'vi': 'Tiếng Việt'
}; 